config/routes.rb
Weaksum::Application.routes.draw do
  resources :operating_systems

  resources :os_vendors

  resources :instances

  get "pages/home"

  root :to => 'pages#home'
  resources :items
  match '/find' => 'items#find', :via => [:post], :as => :find
  

  match '/match/:hash/:tolerance' => 'items#find_fuzzy_matches'
  match '/match/:hash' => 'items#find_fuzzy_matches'
  match '/:hash' => 'items#find'
  match '/:hash_type/:hash' => 'items#find'
  match '/compare/:item1_id/:item2_id' => 'items#compare'
  

end

app/models/instance.rb
class Instance < ActiveRecord::Base
  belongs_to :item
  belongs_to :operating_system
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  # GET /instances
  # GET /instances.json
  def index
    @instances = Instance.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @instances }
    end
  end

  # GET /instances/1
  # GET /instances/1.json
  def show
    @instance = Instance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @instance }
    end
  end

  # GET /instances/new
  # GET /instances/new.json
  def new
    @instance = Instance.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @instance }
    end
  end

  # GET /instances/1/edit
  def edit
    @instance = Instance.find(params[:id])
  end

  # POST /instances
  # POST /instances.json
  def create
    @instance = Instance.new(params[:instance])

    respond_to do |format|
      if @instance.save
        format.html { redirect_to @instance, notice: 'Instance was successfully created.' }
        format.json { render json: @instance, status: :created, location: @instance }
      else
        format.html { render action: "new" }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /instances/1
  # PUT /instances/1.json
  def update
    @instance = Instance.find(params[:id])

    respond_to do |format|
      if @instance.update_attributes(params[:instance])
        format.html { redirect_to @instance, notice: 'Instance was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instances/1
  # DELETE /instances/1.json
  def destroy
    @instance = Instance.find(params[:id])
    @instance.destroy

    respond_to do |format|
      format.html { redirect_to instances_url }
      format.json { head :ok }
    end
  end
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/_form.html.erb
<%= form_for(@instance) do |f| %>
  <% if @instance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instance.errors.count, "error") %> prohibited this instance from being saved:</h2>

      <ul>
      <% @instance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :extension %><br />
    <%= f.text_field :extension %>
  </div>
  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :os_id %><br />
    <%= f.number_field :os_id %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br />
    <%= f.number_field :item_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instances/edit.html.erb
<h1>Editing instance</h1>

<%= render 'form' %>

<%= link_to 'Show', @instance %> |
<%= link_to 'Back', instances_path %>

app/views/instances/index.html.erb
<h1>Listing instances</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Extension</th>
    <th>Path</th>
    <th>Os</th>
    <th>Item</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @instances.each do |instance| %>
  <tr>
    <td><%= instance.name %></td>
    <td><%= instance.extension %></td>
    <td><%= instance.path %></td>
    <td><%= instance.os_id %></td>
    <td><%= instance.item_id %></td>
    <td><%= link_to 'Show', instance %></td>
    <td><%= link_to 'Edit', edit_instance_path(instance) %></td>
    <td><%= link_to 'Destroy', instance, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Instance', new_instance_path %>

app/views/instances/new.html.erb
<h1>New instance</h1>

<%= render 'form' %>

<%= link_to 'Back', instances_path %>

app/views/instances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @instance.name %>
</p>

<p>
  <b>Extension:</b>
  <%= @instance.extension %>
</p>

<p>
  <b>Path:</b>
  <%= @instance.path %>
</p>

<p>
  <b>Os:</b>
  <%= @instance.os_id %>
</p>

<p>
  <b>Item:</b>
  <%= @instance.item_id %>
</p>


<%= link_to 'Edit', edit_instance_path(@instance) %> |
<%= link_to 'Back', instances_path %>