config/routes.rb
Weaksum::Application.routes.draw do
  resources :operating_systems

  resources :os_vendors

  resources :instances

  get "pages/home"

  root :to => 'pages#home'
  resources :items
  match '/find' => 'items#find', :via => [:post], :as => :find
  

  match '/match/:hash/:tolerance' => 'items#find_fuzzy_matches'
  match '/match/:hash' => 'items#find_fuzzy_matches'
  match '/:hash' => 'items#find'
  match '/:hash_type/:hash' => 'items#find'
  match '/compare/:item1_id/:item2_id' => 'items#compare'
  

end

app/models/operating_system.rb
class OperatingSystem < ActiveRecord::Base
  has_many :instances
  has_many :os_vendors
end

app/controllers/operating_systems_controller.rb
class OperatingSystemsController < ApplicationController
  # GET /operating_systems
  # GET /operating_systems.json
  def index
    @operating_systems = OperatingSystem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @operating_systems }
    end
  end

  # GET /operating_systems/1
  # GET /operating_systems/1.json
  def show
    @operating_system = OperatingSystem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @operating_system }
    end
  end

  # GET /operating_systems/new
  # GET /operating_systems/new.json
  def new
    @operating_system = OperatingSystem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @operating_system }
    end
  end

  # GET /operating_systems/1/edit
  def edit
    @operating_system = OperatingSystem.find(params[:id])
  end

  # POST /operating_systems
  # POST /operating_systems.json
  def create
    @operating_system = OperatingSystem.new(params[:operating_system])

    respond_to do |format|
      if @operating_system.save
        format.html { redirect_to @operating_system, notice: 'Operating system was successfully created.' }
        format.json { render json: @operating_system, status: :created, location: @operating_system }
      else
        format.html { render action: "new" }
        format.json { render json: @operating_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /operating_systems/1
  # PUT /operating_systems/1.json
  def update
    @operating_system = OperatingSystem.find(params[:id])

    respond_to do |format|
      if @operating_system.update_attributes(params[:operating_system])
        format.html { redirect_to @operating_system, notice: 'Operating system was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @operating_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operating_systems/1
  # DELETE /operating_systems/1.json
  def destroy
    @operating_system = OperatingSystem.find(params[:id])
    @operating_system.destroy

    respond_to do |format|
      format.html { redirect_to operating_systems_url }
      format.json { head :ok }
    end
  end
end

app/helpers/operating_systems_helper.rb
module OperatingSystemsHelper
end

app/views/operating_systems/_form.html.erb
<%= form_for(@operating_system) do |f| %>
  <% if @operating_system.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operating_system.errors.count, "error") %> prohibited this operating_system from being saved:</h2>

      <ul>
      <% @operating_system.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :os_vendor_id %><br />
    <%= f.number_field :os_vendor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operating_systems/edit.html.erb
<h1>Editing operating_system</h1>

<%= render 'form' %>

<%= link_to 'Show', @operating_system %> |
<%= link_to 'Back', operating_systems_path %>

app/views/operating_systems/index.html.erb
<h1>Listing operating_systems</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Os vendor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @operating_systems.each do |operating_system| %>
  <tr>
    <td><%= operating_system.name %></td>
    <td><%= operating_system.os_vendor_id %></td>
    <td><%= link_to 'Show', operating_system %></td>
    <td><%= link_to 'Edit', edit_operating_system_path(operating_system) %></td>
    <td><%= link_to 'Destroy', operating_system, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Operating system', new_operating_system_path %>

app/views/operating_systems/new.html.erb
<h1>New operating_system</h1>

<%= render 'form' %>

<%= link_to 'Back', operating_systems_path %>

app/views/operating_systems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @operating_system.name %>
</p>

<p>
  <b>Os vendor:</b>
  <%= @operating_system.os_vendor_id %>
</p>


<%= link_to 'Edit', edit_operating_system_path(@operating_system) %> |
<%= link_to 'Back', operating_systems_path %>