config/routes.rb
Weaksum::Application.routes.draw do
  resources :operating_systems

  resources :os_vendors

  resources :instances

  get "pages/home"

  root :to => 'pages#home'
  resources :items
  match '/find' => 'items#find', :via => [:post], :as => :find
  

  match '/match/:hash/:tolerance' => 'items#find_fuzzy_matches'
  match '/match/:hash' => 'items#find_fuzzy_matches'
  match '/:hash' => 'items#find'
  match '/:hash_type/:hash' => 'items#find'
  match '/compare/:item1_id/:item2_id' => 'items#compare'
  

end

app/models/item.rb
class Item < ActiveRecord::Base
  
  has_many :instances
  has_many :metadata
  
  MD5_REGEX = /^[0-9a-f]{32}$/
  SHA1_REGEX = /^[0-9a-f]{40}$/
  SHA256_REGEX = /^[0-9a-f]{64}$/
  FUZZY_REGEX = /^[0-9]+:[^:]+:[^:]+$/
  
  UNIQUENESS_ERROR = "The same file has already been uploaded previously."
  METADATA_IGNORE_LIST = 
  [
    'FileName',
    'Directory',
    'FileSize',
    'FilePermissions',
    'FileModifyDate',
    'ExifToolVersion',
    'Error'
  ]
  
  has_attached_file :upload
  
  validates :description, :length => { :maximum => 500 }
  validates :md5, :uniqueness => { :message => UNIQUENESS_ERROR }
  validates :sha256, :uniqueness => { :message => UNIQUENESS_ERROR }
  validates :sha1, :uniqueness => { :message => UNIQUENESS_ERROR }
  validates_attachment_presence :upload
  validates_attachment_size :upload, :less_than => 100.megabytes
    
  before_save do
    generate_hashes! unless all_hashes_generated?
  end
  
  after_create do
    generate_metadata
  end
  
  def self.find_by_hash(hash, hash_type=nil)
    search_type = hash_type ||= hash_type(hash)
    case search_type.to_sym
    when :md5
      self.find_by_md5(hash)  
    when :sha1
      self.find_by_sha1(hash)
    when :sha256
      self.find_by_sha256(hash)
    when :fuzzy_hash
      self.where(:fuzzy_hash => hash)
    when :unknown
      self.find_by_upload_file_name(hash)
    end
  end
    
  def self.hash_type(hash)
    return :md5 if hash =~ MD5_REGEX
    return :sha1 if hash =~ SHA1_REGEX
    return :sha256 if hash =~ SHA256_REGEX
    return :fuzzy_hash if hash=~ FUZZY_REGEX
    return :unknown
  end
  
  def self.find_fuzzy_matches(fuzzy_hash, lower_tolerance=70, upper_tolerance=100)
    matches = []
    Item.all.each do |item|
      percent_match = Ssdeep.fuzzy_compare(item.fuzzy_hash, fuzzy_hash)
      
      if percent_match <= upper_tolerance && percent_match >= lower_tolerance
        matches << { :item => item, :percent_match => percent_match } 
      end  
    end
    
    matches
  end
  
  def generate_hashes!
    self.generate_hashes
    self.save
  end
  
  def generate_metadata
    file = upload.queued_for_write[:original].path
    metadata = MiniExiftool.new file
    metadata_hash = metadata.to_hash
    metadata_hash.each do |k,v|
      Metadatum.create( { :name => k, :value => v, :item_id => self.id } ) unless METADATA_IGNORE_LIST.include?(k)
    end
  end
  
  def generate_hashes
    file = upload.queued_for_write[:original].path
    self.md5 = self.generate_md5(file)
    self.sha1 = self.generate_sha1(file)
    self.sha256 = self.generate_sha256(file)
    self.fuzzy_hash = self.generate_fuzzy_hash(file)
  end
  
  def generate_new_hashes
    file = upload.path
    self.md5 ||= self.generate_md5(file)
    self.sha1 ||= self.generate_sha1(file)
    self.sha256 ||= self.generate_sha256(file)
    self.fuzzy_hash ||= self.generate_fuzzy_hash(file)
  end
  
  def all_hashes_generated?
    return true if self.md5 && self.sha1 && self.sha256 && self.fuzzy_hash
    false
  end
  
  def generate_md5(file)
    Digest::MD5.file(file).hexdigest
  end
  
  def generate_sha1(file)
     Digest::SHA1.file(file).hexdigest
  end
  
  def generate_sha256(file)
    Digest::SHA256.file(file).hexdigest
  end
  
  def generate_fuzzy_hash(file)
    Ssdeep.hash_file(file).to_s
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def find
    hash_type = params[:hash_type].to_sym
    
    unless hash_type.blank?
      case hash_type
      when :fuzzy_hash
        limits = params[:tolerance].gsub('%','').split(' - ').map(&:to_i)
        @items = Item.find_fuzzy_matches(params[:hash],limits.first, limits.last)
      else
        @item = Item.find_by_hash(params[:hash], hash_type)
      end
    else
      @item = Item.find_by_hash(params[:hash]) 
    end
    
    respond_to do |format|
      format.html { redirect_to @item } if @item
      format.html { render :index } if @items
      format.json { render json: @item }
    end
  end
  
  def find_fuzzy_matches
    tolerance = params[:tolerance]
    hash = params[:hash]
    
    if tolerance
      @item_matches = Item.find_fuzzy_matches(hash, tolerance)
    else
      @item_matches = Item.find_fuzzy_matches(hash)
    end
    
    respond_to  do |format|
      format.html { render :fuzzy_matches }
      format.json { render json: @item_matches }
    end
    
  end

  
  def compare
    @item1 = Item.find(params[:item1_id])
    @item2 = Item.find(params[:item2_id])
    @percent_match = Ssdeep.fuzzy_compare(@item1.fuzzy_hash, @item2.fuzzy_hash)
  end
  
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html { render :new, :layout => false } # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :ok }
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.label :upload, "Select Sample to Analyze" %><br>
  <%= f.file_field :upload %>
  </div>

  <div class="field">
  <%= f.label :upload, "Operating System where sample was discovered " %><br>
  <%= f.file_field :upload %>
  </div>

  <div class="field">
  <%= f.label :description, "Add a description about this sample" %><br>
  <%= f.text_area :description, :cols => 10, :rows => 10 %>
  </div>

  <div class="actions">
    <%= f.submit "Analyze Sample" %>
  </div>
<% end %>

app/views/items/compare.html.erb
<%= @percent_match %>% matching.

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/fuzzy_matches.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Upload file name</th>
    <th>Match %</th>
  </tr>

<% @item_matches.each do |item_match| %>
  <tr>
    <td><%= item_match[:item].upload_file_name %></td>
    <td><%= item_match[:percent_match]%></td>

  </tr>
<% end %>
</table>

<br />

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Upload file name</th>
    <th>Upload content type</th>
    <th>Upload file size</th>
    <th>Upload updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.upload_file_name %></td>
    <td><%= item.upload_content_type %></td>
    <td><%= item.upload_file_size %></td>
    <td><%= item.upload_updated_at %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<div class="popup">
	<h1>New Hash</h1>
	<%= render 'form' %>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @item.upload_file_name %></h1>

<h2>Hashes</h2>
<p>
  <b>Md5:</b>
  <%= @item.md5 %>
</p>

<p>
  <b>Sha1:</b>
  <%= @item.sha1 %>
</p>

<p>
  <b>Sha256:</b>
  <%= @item.sha256 %>
</p>

<p>
  <b>Fuzzy hash:</b>
  <%= @item.fuzzy_hash %>
</p>

<h2>Sample information</h2>
<p>
  <b>Upload file name:</b>
  <%= @item.upload_file_name %>
</p>

<p>
  <b>Upload content type:</b>
  <%= @item.upload_content_type %>
</p>

<p>
  <b>Upload file size:</b>
  <%= @item.upload_file_size %>
</p>

<p>
  <b>Upload updated at:</b>
  <%= @item.upload_updated_at %>
</p>

<h2>Metadata</h2>
<ul>
	<% @item.metadata.each do |metadatum| %>
		<li><strong><%= metadatum.name %></strong>: <%= metadatum.value %></li>
	<% end  %>
</ul>
<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>