config/routes.rb
Weaksum::Application.routes.draw do
  resources :operating_systems

  resources :os_vendors

  resources :instances

  get "pages/home"

  root :to => 'pages#home'
  resources :items
  match '/find' => 'items#find', :via => [:post], :as => :find
  

  match '/match/:hash/:tolerance' => 'items#find_fuzzy_matches'
  match '/match/:hash' => 'items#find_fuzzy_matches'
  match '/:hash' => 'items#find'
  match '/:hash_type/:hash' => 'items#find'
  match '/compare/:item1_id/:item2_id' => 'items#compare'
  

end

app/models/os_vendor.rb
class OsVendor < ActiveRecord::Base
  has_many :operating_systems
end

app/controllers/os_vendors_controller.rb
class OsVendorsController < ApplicationController
  # GET /os_vendors
  # GET /os_vendors.json
  def index
    @os_vendors = OsVendor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @os_vendors }
    end
  end

  # GET /os_vendors/1
  # GET /os_vendors/1.json
  def show
    @os_vendor = OsVendor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @os_vendor }
    end
  end

  # GET /os_vendors/new
  # GET /os_vendors/new.json
  def new
    @os_vendor = OsVendor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @os_vendor }
    end
  end

  # GET /os_vendors/1/edit
  def edit
    @os_vendor = OsVendor.find(params[:id])
  end

  # POST /os_vendors
  # POST /os_vendors.json
  def create
    @os_vendor = OsVendor.new(params[:os_vendor])

    respond_to do |format|
      if @os_vendor.save
        format.html { redirect_to @os_vendor, notice: 'Os vendor was successfully created.' }
        format.json { render json: @os_vendor, status: :created, location: @os_vendor }
      else
        format.html { render action: "new" }
        format.json { render json: @os_vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /os_vendors/1
  # PUT /os_vendors/1.json
  def update
    @os_vendor = OsVendor.find(params[:id])

    respond_to do |format|
      if @os_vendor.update_attributes(params[:os_vendor])
        format.html { redirect_to @os_vendor, notice: 'Os vendor was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @os_vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /os_vendors/1
  # DELETE /os_vendors/1.json
  def destroy
    @os_vendor = OsVendor.find(params[:id])
    @os_vendor.destroy

    respond_to do |format|
      format.html { redirect_to os_vendors_url }
      format.json { head :ok }
    end
  end
end

app/helpers/os_vendors_helper.rb
module OsVendorsHelper
end

app/views/os_vendors/_form.html.erb
<%= form_for(@os_vendor) do |f| %>
  <% if @os_vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@os_vendor.errors.count, "error") %> prohibited this os_vendor from being saved:</h2>

      <ul>
      <% @os_vendor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/os_vendors/edit.html.erb
<h1>Editing os_vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @os_vendor %> |
<%= link_to 'Back', os_vendors_path %>

app/views/os_vendors/index.html.erb
<h1>Listing os_vendors</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @os_vendors.each do |os_vendor| %>
  <tr>
    <td><%= os_vendor.name %></td>
    <td><%= link_to 'Show', os_vendor %></td>
    <td><%= link_to 'Edit', edit_os_vendor_path(os_vendor) %></td>
    <td><%= link_to 'Destroy', os_vendor, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Os vendor', new_os_vendor_path %>

app/views/os_vendors/new.html.erb
<h1>New os_vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', os_vendors_path %>

app/views/os_vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @os_vendor.name %>
</p>


<%= link_to 'Edit', edit_os_vendor_path(@os_vendor) %> |
<%= link_to 'Back', os_vendors_path %>